### ISSUE TITLE
Question: Will this work for GNU Octave too?

### ISSUE THREAD

**Issue by DanielMartensson** [OpenModelica/OMMatlab#14]
Will this work for GNU Octave too?

**Comment by casella** [comment]
I don't think so. This could be considered, provided we have proof that there are enough people intrested. Or, if you are bold, you could try to contribute yourself to the feature development. @DanielMartensson, what do you think?

**Comment by DanielMartensson** [comment]
> I don't think so. This could be considered, provided we have proof that there are enough people intrested. Or, if you are bold, you could try to contribute yourself to the feature development. @DanielMartensson, what do you think?

It seems that somebody have already did that. @casella 
https://github.com/PR-DC/PRDC_OMOctave

Good work!

**Comment by casella** [comment]
Interesting indeed. I'll ask the developer if he wants to provide this directly to the OpenModelica source code. We can't do that, because we are releasing OMC with dual licensing (GPL and OSMC-PL), while this package is GPL'd

**Comment by DanielMartensson** [comment]
> Interesting indeed. I'll ask the developer if he wants to provide this directly to the OpenModelica source code. We can't do that, because we are releasing OMC with dual licensing (GPL and OSMC-PL), while this package is GPL'd

@casella 
I have one question about the API. If I have OpenModelica and I want to use the API trougth Octave/Matlab. Can I pass inputs into the `.mo` file and recieve outputs if I want to run a simulation? 

I have idéas if I should replace `ODE45` in MATLAB/Octave with OpenModelica instead. But I don't know if it's possible to call `.mo` files with input arguments and recieve outputs back to Matlab/Octave.

As I understand the API, I can only simulate a model without initial states? And I cannot recieve back data as .e.g an array back?

That would be awesome I this API could to that because I really need a Simulink alternative for Octave.

**Comment by casella** [comment]
@arun3688 can you comment about that? Thanks!

**Comment by arun3688** [comment]
@DanielMartensson I did not clearly understand what you want to do with the API, Based on my understanding the `simulate` API will simulate the modelica model and the results are written to mat file or csv file. To read the simulation results you should use `getSolutions` API  see the documentation https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/ommatlab.html. Otherwise it would be helpful if you can show your matlab script on what you are doing and what you need

**Comment by DanielMartensson** [comment]
@arun3688 

Can I simulate a model with inputs e.g initial states?

I don't have matlab. I have Octave. There is a library who looks exactly like OMMatlab library, but it's working for Octave. So I guess it's almost the same code.

**Comment by casella** [comment]
@arun3688 the idea would be to embed OMOctave in OpenModelica instead of having it as a separate tool. Can you guide @DanielMartensson to prepare a suitable PR?

**Comment by arun3688** [comment]
@casella @DanielMartensson , I have now implemented `OMOctave` package directly in OpenModelica with some minimal effort and it is available in the following repository https://github.com/OpenModelica/OMOctave, Please follow the  instruction in `ReadME.md` for using the package in Octave

**Comment by DanielMartensson** [comment]
> @casella @DanielMartensson , I have now implemented `OMOctave` package directly in OpenModelica with some minimal effort and it is available in the following repository https://github.com/OpenModelica/OMOctave, Please follow the instruction in `ReadME.md` for using the package in Octave

@casella @arun3688 Wow! Great! 

I have plans to use this library for simulation. Is there any way for me to call the simulation with initials states? I find that very useful. 

For example: If I have a hanging load M that are connected to a spring K and a damper B. Then I want to call that simulation with initial state X for t = 0 and M, K, B as parameters. Then I want to recieve the outputs back. I have been reading the API, but cannot find a such information.

**Comment by arun3688** [comment]
> I have one question about the API. If I have OpenModelica and I want to use the API trougth Octave/Matlab. Can I pass inputs into the `.mo` file and recieve outputs if I want to run a simulation?
> 
> I have idéas if I should replace `ODE45` in MATLAB/Octave with OpenModelica instead. But I don't know if it's possible to call `.mo` files with input arguments and recieve outputs back to Matlab/Octave.
> 
> As I understand the API, I can only simulate a model without initial states? And I cannot recieve back data as .e.g an array back?
> 
> That would be awesome I this API could to that because I really need a Simulink alternative for Octave

It is possible to set inputs to the ".mo" file via the `setInputs` API, An example would be 

`omc.setInputs(["Tc=300";"Ti=350";"Vdi=100";"cAi=1"])
`

**Comment by DanielMartensson** [comment]
> > I have one question about the API. If I have OpenModelica and I want to use the API trougth Octave/Matlab. Can I pass inputs into the `.mo` file and recieve outputs if I want to run a simulation?
> > I have idéas if I should replace `ODE45` in MATLAB/Octave with OpenModelica instead. But I don't know if it's possible to call `.mo` files with input arguments and recieve outputs back to Matlab/Octave.
> > As I understand the API, I can only simulate a model without initial states? And I cannot recieve back data as .e.g an array back?
> > That would be awesome I this API could to that because I really need a Simulink alternative for Octave
> 
> It is possible to set inputs to the ".mo" file via the `setInputs` API, An example would be
> 
> `omc.setInputs(["Tc=300";"Ti=350";"Vdi=100";"cAi=1"]) `

Ah, I see. The function `.setInputs()`. And then I load the result from the `.mat` file. Perfect. I think I got all what I need to make simulations.

Thank you.

**Comment by arun3688** [comment]
@DanielMartensson Yes You have to look into the advanced  API feature https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/ommatlab.html#advanced-ommatlab-features

**Comment by casella** [comment]
@DanielMartensson thanks for you input, and thanks @arun3688 for the implementation.

@DanielMartensson, if you are happy with the interface in general please close this ticket. If you have specific questions or issue, please open separate tickets which are focused on the specific issue.

Thanks!
