### ISSUE TITLE
Invalid installation instructions

### ISSUE THREAD

**Issue by hkiel** [OpenModelica/OMMatlab#2]
Do not edit `pathdef.m` ( -> `% DO NOT MODIFY THIS FILE.  IT IS AN AUTOGENERATED FILE.`), but use `pathtool` to add the path.
Do not edit `classpath.txt`, but create file `javaclasspath.txt` in preferences folder (can be found by `prefdir`)

**Comment by arun3688** [comment]
@hkiel  Yes agreed  for javaclasspath.txt, But for pathtool, i am not sure the path is saved for future session

**Comment by arun3688** [comment]
@hkiel  Updated the install instruction, pathtool works

**Comment by hkiel** [comment]
You need to save the new path wih pathtool

**Comment by arun3688** [comment]
I have changed the instruction, i think i can close this issue
