### ISSUE TITLE
getSolutions bug for large numbers

### ISSUE THREAD

**Issue by MohammadHadiAlizadeh** [OpenModelica/OMMatlab#20]
Hi.
Consider the following model

```mo
model test2
  parameter Real a_Pi=-1.55555555555e16;
  Real x; 
equation
  der(x) = a_Pi;
end test2;
```

When trying to simulate using the following code:

```matlab
clear all
import OMMatlab.*
omc=OMMatlab();
omc.ModelicaSystem("test2.mo","test2");
omc.setSimulationOptions(["startTime=0","stopTime=0"]);
omc.simulate()
a=omc.getSolutions("a_Pi")
```
it returns :
```
a =

  1×1 cell array

    {["-1.555555555e"    "16"    "-1.555555555e"    "16"]}
```
that is a deprecated form of -1.5555555e16. It happens not only for parameters but also for large state variables with many decimals when trying to get them by `getSolutions`.

**Comment by MohammadHadiAlizadeh** [comment]
It happens for the large numbers with a few of decimals too

``a_Pi=-1.5555e16;``

```
a =

  1×1 cell array

    {["-1.5555e"    "16"    "-1.5555e"    "16"]}
```

**Comment by MohammadHadiAlizadeh** [comment]
@arun3688  can you please have a look at this problem?

**Comment by arun3688** [comment]
@i will soon look into the issue, as i am occupied with other works

**Comment by MohammadHadiAlizadeh** [comment]
@arun3688 thanks. I'll be looking forward to hearing from you.

**Comment by arun3688** [comment]
@MohammadHadiAlizadeh This issue is fixed with your commit https://github.com/OpenModelica/OMMatlab/commit/88dda46147e92dc1d98730dd694f349b3f8eee81. It is a parse Error thanks for the fix
