### ISSUE TITLE
Observer

### ISSUE THREAD

**Issue by MohammadHadiAlizadeh** [OpenModelica/OMMatlab#25]
Hello,
I'm not sure if I'm asking this question in the right part.

Is there any way to design nonlinear state estimators like EKF or UKF in the OpenModelica?

**Comment by casella** [comment]
The best way to do that is to export the system model as FMI and then build the EKF/UKF around that. One of my master's students is currently doing that in Python.

**Comment by MohammadHadiAlizadeh** [comment]
@casella , Thanks.

Does any specific python package exist for doing this? As you know, EKF needs discrete function evaluations and the Jacobian supported by FMU needs to be exported.

**Comment by casella** [comment]
You can check these two references:
- https://www.merl.com/publications/docs/TR2020-031.pdf
- https://ep.liu.se/en/conference-article.aspx?series=ecp&issue=96&Article_No=68

We are using implicit Euler to get a discrete-time formulation, we use FMU-supplied jacobians, and also use sparse matrices, which are useful if your system has more than a few dozen states and has a sparse structure, which is usually the case for large-scale systems, that only have local neighbourhood connections.

**Comment by MohammadHadiAlizadeh** [comment]
Thank you
