### ISSUE TITLE
'ZMQ.context' error

### ISSUE THREAD

**Issue by Sajjadkoohi1999** [OpenModelica/OMMatlab#31]
Dear all
I received a error in Matlab as follows:

Unable to resolve the name 'ZMQ.context'.
Error in OMMatlab (line 113)
            obj.context=ZMQ.context(1);

Could you please guide me to solve the problem?

**Comment by MohammadHadiAlizadeh** [comment]
@Sajjadkoohi1999 Does this happen during the simulation or at the beginning of the code execution?
@arun3688 What is your opinion? Is this an installation issue?

**Comment by Sajjadkoohi1999** [comment]
It happened at the beginning.

**Comment by arun3688** [comment]
@Sajjadkoohi1999 it is happening because you have not installed the jeromq jar files in the javaclasspath, please follow the installation instructions provided here https://github.com/OpenModelica/OMMatlab/blob/master/README.md
