### ISSUE TITLE
Variable are not changing the value

### ISSUE THREAD

**Issue by ismaelpereira** [OpenModelica/OMMatlab#32]
Hello guys, I have a windows 10 installed and it's my first time using the OMMatlab interface. I have the Matlab R2022b and Open Modelica 1.22.3 installed on my PC (installed on C:/). I pick an example here and when i change the mass and the stopTime it changes on the output but it's no plotting with the right values.

I already update my java, add the /bin on the Path environment variable on Windows and nothing is happening. What can it be? 

The steps I install was create a folder on the Matlab toolbox folder called ommatlab, and run the pathtool and add this directory

Then i runned the prefdir and add the javaclasspath.txt and past this path `C:/Users/luisa/Downloads/OMMatlab-master/OMMatlab-master/jeromq-0.4.4-SNAPSHOT.jar` (It doesn't make any difference if I use / or \) 

This is my file on Matlab called *acionador.m*
```
import OMMatlab.*
omc = OMMatlab();
omc.sendExpression("getVersion()")
omc.sendExpression('loadFile("exemplo.mo")')
omc.ModelicaSystem("exemplo.mo","exemplo")
omc.sendExpression("getClassNames()")
omc.getParameters(["m","E"])
omc.setParameters("m = 0.7")
omc.getParameters(["m","E"])
omc.getSimulationOptions(["stopTime","stepSize"])
omc.setSimulationOptions(["stopTime=2","stepSize=0.001"])
omc.getSimulationOptions(["stopTime","stepSize"])
omc.simulate();
omc.sendExpression("simulate(exemplo)")
omc.sendExpression("plot(h)")
```

This is the output from this file

```
>> acionador
ans = 

    "OpenModelica v1.22.3 (64-bit)"
ans = 
    "true"
ans = 
    "true"
ans = 
    "C:/Users/luisa/AppData/Local/Temp/tp6a06a83f_8709_4da3_a5e2_5c1e7083784c"
ans = 
  1×4 string array
    "ModelicaServices"    "Complex"    "Modelica"    "exemplo"
ans = 
  1×2 string array
    "0.1"    "220.0"
ans = 
  1×2 string array
    "0.7"    "220.0"
ans = 
  1×2 string array
    "1"    "0.002"
ans = 
  1×2 string array
    "2"    "0.001"
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
LOG_SUCCESS       | info    | The simulation finished successfully.
ans =
     0
ans = 
  struct with fields:

           resultFile: "C:/Users/luisa/AppData/Local/Temp/tp6a06a83f_8709_4da3_a5e2_5c1e7083784c/exemplo_res.mat"
    simulationOptions: "startTime = 0.0, stopTime = 1.0, numberOfIntervals = 500, tolerance = 1e-06, method = 'dassl', fileNamePrefix = 'exemplo', options = '', outputFormat = 'mat', variableFilter = '.*', cflags = '', simflags = ''"
             messages: "LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.↵LOG_SUCCESS       | info    | The simulation finished successfully.↵"
         timeFrontend: "0.1742779"
          timeBackend: "0.0816281"
          timeSimCode: "0.0064083"
        timeTemplates: "0.017791"
          timeCompile: "6.2424061"
       timeSimulation: "0.0984259"
            timeTotal: "6.6213661"
ans = 
    "true"
``` 

You can see on the second input from `omc.getParameters(["m","E"])` m is already 0.7 and the stoptime have the same behavior, but it's still plotting the graph with the stopTime 1

Do you guys have any clue about this problem?

**Comment by arun3688** [comment]
@ismaelpereira from what you wrote above, I can see that you are combining both `sendExpression` and `ModelicaSystem`  constructor in the same script and that is not correct so you have to use either of the one for example 

```
import OMMatlab.*
omc = OMMatlab();
omc.ModelicaSystem("exemplo.mo","exemplo")
omc.getParameters(["m","E"])
omc.setParameters("m = 0.7")
omc.getParameters(["m","E"])
omc.getSimulationOptions(["stopTime","stepSize"])
omc.setSimulationOptions(["stopTime=2","stepSize=0.001"])
omc.getSimulationOptions(["stopTime","stepSize"])
omc.simulate();
omc.getSolutions("m");
```

**Comment by ismaelpereira** [comment]
Hey @arun3688 Thanks for the response. This helps me to understand better. This code that you sent me works, but i need in the end the `omc.sendExpression("plot(h)")` method working. If I add on the last line this is my code 
```
import OMMatlab.*
omc = OMMatlab();
omc.ModelicaSystem("exemplo.mo","exemplo")
omc.getParameters(["m","E"])
omc.setParameters("m = 0.7")
omc.getParameters(["m","E"])
omc.getSimulationOptions(["stopTime","stepSize"])
omc.setSimulationOptions(["stopTime=2","stepSize=0.001"]);
omc.getSimulationOptions(["stopTime","stepSize"])
omc.simulate();
omc.getSolutions("m");
omc.sendExpression("plot(h)")
``` 

This are the outputs

```
ans = 

    "true"


ans = 

    "C:/Users/Ismael/AppData/Local/Temp/tp3ad5f63c_57c0_46af_8d22_69fb33c9a853"


ans = 

  1×2 string array

    "0.1"    "220.0"


ans = 

  1×2 string array

    "0.7"    "220.0"


ans = 

  1×2 string array

    "1"    "0.002"


ans = 

  1×2 string array

    "2"    "0.001"

LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
LOG_SUCCESS       | info    | The simulation finished successfully.

ans =

     0


ans = 

    "false"
```

You can see that the plot function is returning a false value, how can I plot the graph not using the sendExpression?

**Comment by arun3688** [comment]
@ismaelpereira you can plot the graph using some other plot tools in matlab or you can get the result file after simulation

```
>>> omc.simulate()
>>> omc.resultfile // this will provide the location of result file 
```
and as i said sendExpression and ModelicaSystem are two different constructor and you cannot simply use the plot, you have to specify the result file location when used with ModelicaSystem , see the API https://build.openmodelica.org/Documentation/OpenModelica.Scripting.plot.html
So you have to use the plot to specify the result file

`>>> omc.sendExpression(plot(h, fileName=\"a.mat\"))`

`getSolutions` API will read the mat file and provide the result data.

**Comment by ismaelpereira** [comment]
Sorry @arun3688 I had some difficult to understand. If I am using the ModelicaSystem constructor should I not use the `sendExpression` method? I saw on the documentation that I can use the `plot(h, externalWindow=true);` to plot, but it 's returning false, what can it be?

**Comment by ismaelpereira** [comment]
@arun3688 I was able to plot using the correct fileName, thanks for the help. I just want to understand better this. If I am using the ModelicaSystem constructor should I not use the sendExpression method? After the answer you can close the issue

**Comment by arun3688** [comment]
@ismaelpereira You can use the sendExpression within ModelicaSystem constructor, based on the needs you have for example you cannot do this 

```
omc.sendExpression('loadFile("exemplo.mo")')
omc.ModelicaSystem("exemplo.mo","exemplo")
omc.sendExpression("simulate(exemplo)")
omc.simulate()
```
What happens here is two separate instances of `OMCSession` are used here and the changes you make in one session will not be reflected in the other and that is why your plot did not work, `ModelicaSystem` constructor has some advanced feature of setting parameters and other settings options, and it basically used for post processing of results,  When using ModelicaSystem and if you want to plot the graph,  you have to specify the correct `fileName` otherwise it will not work. because plot API basically uses the last simulated result file and as is said two seperate omc sessions are used and they are independent of each other
