### ISSUE TITLE
changing values and simulate

### ISSUE THREAD

**Issue by adrcarrui** [OpenModelica/OMMatlab#5]
Hi!

I've been working for a while trying to change some values and simulate again but is always keeping the same result.

I try to simulate BouncingBall for 1 time, and e = 0.7 I changed it to e=1.4 and simulate again but the value is 0.7 again. What can I do to keep the new one? (I used `system("./BouncingBall -override=e="+String(1.4)+" -r=BouncingBall" + "_res.mat");`)

**Comment by adrcarrui** [comment]
I thought about changing the xml init file. I changed the value there with `omc.sendExpression('setInitXmlStartValue(BouncingBall.xml,e,10,BouncingBall.xml')`. I could see the change into an xml reader. So I believed I had gotten it, I simulated the model again but I got the same value of e (0.7 not 10). Is there any possibility to change the model variables and simulate to see the changes? If there is the possibility what am I doing wrong? I think I need to execute a function to tell the model the changes on Matlab but which one?

Maybe there is an easier way to do what I want. It's just simulate a model, get the results, change it, simulate again, see the new results. I tried all that I though, maybe someone can give me another point of view.

**Comment by arun3688** [comment]
Hi , i just checked that executing system("BouncingBall.exe") does not work from matlab in windows, it does not create the result file in windows, but if u try  winopen('BouncingBall.exe') does works and creates the result files in windows, and you can see the changes in the result file but you cannot pass the override flag,  these are the steps to follow

     >>omc.sendExpression('loadFile("BouncingBall.mo")')
     >>omc.sendExpression('buildModel(BouncingBall)')
     >>omc.sendExpression('setInitXmlStartValue("BouncingBall_init.xml","e","25","BouncingBall_init.xml")')
     >>winopen('BouncingBall.exe')

if you want to pass the override flag, follow these steps
      >>  omc.sendExpression('loadFile("BouncingBall.mo")')
      >>  omc.sendExpression('buildModel(BouncingBall)')

and then open the windows cmd prompt and from the path to exe file run
      >>  BouncingBall.exe -override=e=12

**Comment by adrcarrui** [comment]
I tried this: 

>  >>omc.sendExpression('loadFile("BouncingBall.mo")')
>  >>omc.sendExpression('buildModel(BouncingBall)')
>  >>omc.sendExpression('setInitXmlStartValue("BouncingBall_init.xml","e","25","BouncingBall_init.xml")')
>  >>winopen('BouncingBall.exe')

and this:

> if you want to pass the override flag, follow these steps
> >> omc.sendExpression('loadFile("BouncingBall.mo")')
> >> omc.sendExpression('buildModel(BouncingBall)')
> 
> and then open the windows cmd prompt and from the path to exe file run
> >> BouncingBall.exe -override=e=12

I got the same error.

![github6](https://user-images.githubusercontent.com/18417143/39125262-ab0777c4-46fe-11e8-9f4c-66900701592e.JPG)

The error says the application could not start correctly.

I tried to find a solution but I couldn't find it. I read that there are some problems with my C++ packages, I reinstalled it but I got the same error. Any hint about it?

Thanks.

**Comment by arun3688** [comment]
Add c:openmodelica /bin to your system path

**Comment by adrcarrui** [comment]
I added it

![github7](https://user-images.githubusercontent.com/18417143/39171806-305db2de-47a0-11e8-9f59-15a9e288c0b5.JPG)

However I getting the same error.

**Comment by arun3688** [comment]
No you should add it to path environment variable

**Comment by adrcarrui** [comment]
Do you say I have to add it to "Path" into the user environment variable?

**Comment by hkiel** [comment]
yes

**Comment by adrcarrui** [comment]
Ok I did it. Thanks! I'll close the thread.

**Comment by adrcarrui** [comment]
Hi again!

I want to change the data inside an array. I was trying to do it in all the ways I though but I couldn't make it. 

I only can change paremeters right now, what have I to do to change arrays, variables...?

Moreover, I'm interested to edit the data inside a block such a timetable (Modelica.Blocks.Sources.TimeTable) or input (Modelica.Blocks.Interfaces.RealInput), so how can I do it?

All the changes I want to do is through Matlab.
