### ISSUE TITLE
OMMatlab lots of invalid Matlab syntax (Matlab R2015b)

### ISSUE THREAD

**Issue by RSchiemann** [OpenModelica/OMMatlab#6]
Hi,

I just wanted to give OMMatlab a try and downloaded it. After trying to run it the first time, Matlab found a *lot* of syntax errors in OMMatlab.m all of which are due to unallowed use of the " character.

Example from line 85:
libmsg = obj.sendExpression("loadFile( """+ libraries{n} +""")");

The syntax used is very invalid Matlab code. First, Matlab only accepts the ' character for string definition. Second, in Matlab language, strings are concatenated using vector notation [string1 string2] instead of adding with a + operator.

I am very curious to learn how anybody was able to execute OMMatlab in view of these syntax errors? Or is everybody trying in Octave, which is much less stringent in terms of Matlab syntax?

I would appreciate if OMMatlab would be fixed to be actual Matlab. I can give advice if needed.

BR,
Robert

**Comment by arun3688** [comment]
@RSchiemann  I think you are using very old version of Matlab, Look into the documentation for more details regarding Strings. https://se.mathworks.com/help/matlab/ref/string.html. You need to update to latest version and test it .  And this line of code 

libmsg = obj.sendExpression("loadFile( """+ libraries{n} +""")");

The + operator here is not concatenation, it is just accepting arguments for the omc API.

It is developed using MAtlab R2017b. I hope this helps

**Comment by RSchiemann** [comment]
@arun3688 Thank you for your quick and enlightening answer. Indeed it helps and I would not have thought that the 4-year-old Matlab I use might be the issue. 
Will get a newer Matlab and try again. Thanks!

**Comment by hkiel** [comment]
@arun3688 I'm using R2017b as well, and I'm missing xml2struct function
`Undefined function or variable 'xml2struct'.`

I downloaded it from https://de.mathworks.com/matlabcentral/fileexchange/28518-xml2struct but then I get `Reference to non-existent field 'Children'.`

**Comment by arun3688** [comment]
@hkiel , Hi i think there is this version which is available from R2016b https://se.mathworks.com/matlabcentral/fileexchange/58700-xml2struct-with-bug-fix-and-added-features

But for me i did not download this function, the package was already available from 2017b

**Comment by hkiel** [comment]
@arun3688 The package you referenced also results in the same error. 
```
>> import OMMatlab.*;
>> omc=OMMatlab();
>> omc.sendExpression("getVersion()")

ans =

"OpenModelica 1.13.0"


>> omc.ModelicaSystem('BouncingBall.mo','BouncingBall')
Reference to non-existent field 'Children'.

Error in OMMatlab/xmlparse (line 118)
                root = xdoc(2).Children;

Error in OMMatlab/ModelicaSystem (line 110)
            xmlparse(obj);
```

**Comment by arun3688** [comment]
@hkiel can you try to load the xml file like this in the matlab terminal and see what you get

>> doc=xml2struct('BouncingBall_init.xml')

doc = 

  1×2 struct array with fields:

    Name
    Attributes
    Data
    Children

**Comment by hkiel** [comment]
I get this:
```
>> doc=xml2struct('BouncingBall_init.xml')

doc = 

  struct with fields:

    fmiModelDescription: [1×1 struct]

```

**Comment by arun3688** [comment]
@hkiel  I think you are using different version of xml2struct, For me i did not download anything, the default matlab2017b had this library and also another user from norway he also tested it, he did not have any problems, Can yout try to download this version and run the same and see what you get as output https://github.com/joe-of-all-trades/xml2struct/blob/master/xml2struct.m

**Comment by hkiel** [comment]
@arun3688 I get the same output with that version. And xml2struct was not installed, and I have full campus version. The same for R2018a on win64. No xml2struct() funktion available. Maybe that is packaged in some toobox I have no access to!?!
Can you show your output of `which xml2struct`?

**Comment by arun3688** [comment]
@hkiel you are correct, it is with some toolbox 

>> which xml2struct
C:\Program Files\Matlab\R2017b\toolbox\bioinfo\biodemos\xml2struct.m

if this "bioinfo" toolbox cannot be obtained on all matlab version, should i change to default xmlread

**Comment by hkiel** [comment]
@arun3688 That is the "Bioinformatics Toolbox", which is not part of standard installation.
You should at least add a hint in the installation documentation (installed size is 205MB - just for `xml2struct`...) I would vote to use `xmlread` instead which is matlab core.
I installed bioinfo toolbox and now it works as expected.

I suggest to not name your variable `doc`: 
```
Error: "doc" was previously used as a variable, conflicting with its use here as
the name of a function or command.
See "How MATLAB Recognizes Command Syntax" in the MATLAB documentation for
details.
```

**Comment by arun3688** [comment]
@hkiel , Yes i will change it to default xmlread

**Comment by RSchiemann** [comment]
has the usage of xml2struct already been replaced by xmlread, according to above discussion?

**Comment by arun3688** [comment]
@RSchiemann  No but it will be soon changed.

**Comment by arun3688** [comment]
@RSchiemann   @hkiel   Changed the xmlparsing to matlab core xmlread,   xml2stuct is removed. Check it

**Comment by arun3688** [comment]
This is fixed with https://github.com/OpenModelica/OMMatlab/commit/deb63f5640b0921fd13c1e52c613203be08fc3a6
