### ISSUE TITLE
Minor bug, regular expression, output signals non-negative

### ISSUE THREAD

**Issue by untervek** [OpenModelica/OMMatlab#9]
Some of my torque signals were non-zero when calling omc.getSolutions() because parseExpression() missed the signs. But when I changed line 855 to the following, everything worked:
final=regexp(args,'"(.*?)"|[{}()=]|[-a-zA-Z0-9_.]+','match');
(I just added the first minus in [-a-zA-Z0-9_.])

**Comment by arun3688** [comment]
@untervek thanks for pointing the issue, can you make a PR, with the changes you made

**Comment by arun3688** [comment]
@this is fixed with https://github.com/OpenModelica/OMMatlab/commit/4a68ace515be1c41b19b08713f0809dd42c275b3
